import React from "react";

export const routes = [
  {
    to: null,
    title: "Creación de componentes",
    description: "",
    component: React.lazy(() => import("../pages/Home")),
  },
  {
    to: "Ejem1",
    title: "Componente usando clases",
    description: "Muestra como crear un componente usando clases. Obsoleto.",
    component: React.lazy(() => import("../pages/Ejem1")),
  },
  {
    to: "Ejem2",
    title: "Componente usando funciones simples",
    description: "Muestra como crear un componente usando funciones clasicas.",
    component: React.lazy(() => import("../pages/Ejem2")),
  },
  {
    to: "Ejem3",
    title: "Componente usando funciones tipo flecha",
    description: "Muestra como crear un componente usando funciones tipo flecha.",
    component: React.lazy(() => import("../pages/Ejem3")),
  },
  {
    to: "Ejem4",
    title: "Componente condicionales",
    description: "Muestra como crear condiciones en React.",
    component: React.lazy(() => import("../pages/Ejem4")),
  },
  {
    to: null,
    title: "Props",
    description: "",
    component: React.lazy(() => import("../pages/Home")),
  },
  {
    to: "Ejem5",
    title: "Pasar props a un componente",
    description: "Muestra como se pueden pasar valores a un componente",
    component: React.lazy(() => import("../pages/Ejem5")),
  },
  {
    to: "Ejem6",
    title: "Estilado de componentes",
    description: "Como dar fomato a los componentes introducidos",
    component: React.lazy(() => import("../pages/Ejem6")),
  },
  {
    to: "Ejem7",
    title: "Pasando funciones como props",
    description: "Uso de funciones en las props",
    component: React.lazy(() => import("../pages/Ejem7")),
  },
  {
    to: "Ejem8",
    title: "Modificacion de las props",
    description: "Uso de funciones en las props",
    component: React.lazy(() => import("../pages/Ejem8")),
  },
  {
    to: "Ejem9",
    title: "Children",
    description: "Pasar propiedades por el children",
    component: React.lazy(() => import("../pages/Ejem9")),
  },
  {
    to: "Ejercicio 0",
    title: "Pasar de grados farengeith",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio0")),
  },
  {
    to: "Ejercicio 1",
    title: "Card personalizado",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio1")),
  },
  {
    to: "Ejercicio 2",
    title: "Calculadora",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio2")),
  },
  {
    to: "Ejem10",
    title: "Eventos",
    description: "Manejo de eventos en React",
    component: React.lazy(() => import("../pages/Ejem10")),
  },
  {
    to: null,
    title: "Manejo del estado",
    description: "",
    component: React.lazy(() => import("../pages/Home")),
  },
  {
    to: "Ejem11",
    title: "Manejo del estado",
    description: "Manejo del estado en React",
    component: React.lazy(() => import("../pages/Ejem11")),
  },
  {
    to: "Ejercicio 3",
    title: "Ejercicio 3",
    description: "Mostrar y ocultar texto",
    component: React.lazy(() => import("../pages/Ejercicio3")),
  },
  {
    to: "Ejem12",
    title: "Manejo del estado 2",
    description: "Como se renderiza el componente",
    component: React.lazy(() => import("../pages/Ejem12")),
  },
  {
    to: "Ejem13",
    title: "Propagacion del estado",
    description: "El estado se propaga",
    component: React.lazy(() => import("../pages/Ejem13")),
  },
  {
    to: "Ejercicio 4",
    title: "Ejercicio 4",
    description: "Lanzamiento de un dado",
    component: React.lazy(() => import("../pages/Ejercicio4")),
  },
  {
    to: "Ejercicio 5",
    title: "Ejercicio 5",
    description: "Crea un componente Boton",
    component: React.lazy(() => import("../pages/Ejercicio5")),
  },
  {
    to: "Ejem14",
    title: "Inicializacion del esetado",
    description: "Como inicializar el estado",
    component: React.lazy(() => import("../pages/Ejem14")),
  },
  {
    to: "Ejem15",
    title: "Mostrar varios elementos",
    description: "Usamos el map para mostrar varios elementos",
    component: React.lazy(() => import("../pages/Ejem15")),
  },
  {
    to: "Ejercicio 6",
    title: "Ejercicio 6",
    description: "Selleccionar elementos de una lista",
    component: React.lazy(() => import("../pages/Ejercicio6")),
  },
  {
    to: null,
    title: "Efectos",
    description: "",
    component: React.lazy(() => import("../pages/Home")),
  },
  {
    to: "Ejem16",
    title: "Ciclo de vida",
    description: "Uso del hook useEffect",
    component: React.lazy(() => import("../pages/Ejem16")),
  },
  {
    to: "Ejem17",
    title: "Ciclo de vida",
    description: "Desmontar el estado",
    component: React.lazy(() => import("../pages/Ejem17")),
  },
  {
    to: "Ejem18",
    title: "Conectandome a apis",
    description: "Obteniendo lista de pokemons",
    component: React.lazy(() => import("../pages/Ejem18")),
  },
  {
    to: "Ejem19",
    title: "Conectandome a apis promiseAll",
    description: "Obteniendo lista de pokemons con foto",
    component: React.lazy(() => import("../pages/Ejem19")),
  },
  {
    to: "Ejem20",
    title: "Eventos del teclado",
    description: "Capturar eventos del teclado",
    component: React.lazy(() => import("../pages/Ejem20")),
  },
  {
    to: "Ejercicio 7",
    title: "Ejercicio 7",
    description: "Bitcoins",
    component: React.lazy(() => import("../pages/Ejercicio7")),
  },
  {
    to: "Ejem21",
    title: "Problemas con el useEffect",
    description: "Bucles infinitos",
    component: React.lazy(() => import("../pages/Ejem21")),
  },
  {
    to: "Ejem22",
    title: "Formularios simples",
    description: "Control de formularios",
    component: React.lazy(() => import("../pages/Ejem22")),
  },
  {
    to: "Ejem23",
    title: "Formularios con campos multiples",
    description: "Control de formularios",
    component: React.lazy(() => import("../pages/Ejem23")),
  },
  {
    to: "Ejercicio 8",
    title: "Ejercicio 8",
    description: "Bitcoins",
    component: React.lazy(() => import("../pages/Ejercicio8")),
  }, 
  {
    to: "Ejem24",
    title: "Hooks personalizados",
    description: "Crear nuestros propios hooks",
    component: React.lazy(() => import("../pages/Ejem24")),
  },
  {
    to: "Ejercicio 9",
    title: "Ejercicio 8",
    description: "Bitcoins",
    component: React.lazy(() => import("../pages/Ejercicio9")),
  }, 
  {
    to: "Ejercicio 10",
    title: "Ejercicio 8",
    description: "Bitcoins",
    component: React.lazy(() => import("../pages/Ejercicio10")),
  }, 
  {
    to: "Ejem27",
    title: "Manejo del contexto",
    description: "Con useContect",
    component: React.lazy(() => import("../pages/Ejem27")),
  },
  {
    to: "Ejercicio 12",
    title: "Ejercicio 12",
    description: "Ejercicio mostrar, añadir y eliminar nombres",
    component: React.lazy(() => import("../pages/Ejercicio12")),
  }, 
  {
    to: "Ejercicio 13",
    title: "Ejercicio 13",
    description: "Maquinas de cafe",
    component: React.lazy(() => import("../pages/Ejercicio13")),
  }, 
];
